-module(prob2).
-export([run/1]).
%%
%% Each new term in the Fibonacci sequence is generated by adding the previous two terms.
%% By starting with 1 and 2, the first 10 terms will be:
%% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%% Find the sum of all the even-valued terms in the sequence which do not exceed four million.
%%
run(B) ->
    total_fib(1,1,0,B).
%%
%%
total_fib(F,S,Sum,B) ->
    Bool = (F rem 2) == 0,
    if Bool ->
	    Bool2 = F > B,
	    if Bool2 ->
		    Sum;
	       true ->
		    total_fib(S,F+S,Sum+F,B)
	    end;
       true ->
	    total_fib(S,F+S,Sum,B)
    end.
%%
%%  
